ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/pwm/pwm_v1/include/
obj-$(CONFIG_PRI_CAMPING_LIGHT) := camping_light.o