#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_GOODIX_GW9518_FINGERPRINT) += goodix-gw9518/
obj-$(CONFIG_FINGERPRINT_FOCALTECH_REE_ATA) += focaltech_ree_ata/
obj-$(CONFIG_PRI_FP_DOOGEE_CUSTOMER) += doogee/
obj-$(CONFIG_PRI_FINGER_ATA_NODE) += pri_finger_ftm_node/
obj-$(CONFIG_PRI_FP_DOOGEE_CUSTOMER) += doogee/

