#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
#obj-$(CONFIG_PRI_HARDWARE_INFO) += hardware_info/
obj-$(CONFIG_CAMERA_GC0301)		+= pri_dual_camera/
#pri add by xuejian for gesture 20230210 start
obj-$(CONFIG_PRI_COMMON_NODE) += pri_common_node/
#pri add by xuejian for gesture 20230210 end
#add by driver for pixel_manager 20231124 start
obj-$(CONFIG_PRI_PIXEL_MANAGER) += pixel_manager/
#add by driver for pixel_manager 20231124 end

#drv-add by shenwenbin for oled panel 20231213 start
obj-$(CONFIG_PRI_OLED_NODE) += pri_oled_node/
#drv-add by shenwenbin for oled panel 20231213 end

obj-$(CONFIG_PRI_AW2016A)		+= aw2016a/
obj-$(CONFIG_LEDS_AW22127)		+= aw22127/
obj-$(CONFIG_LEDS_AW210XX)		+= aw210xx/
obj-$(CONFIG_PRI_ENDOSCOPE) += endoscope/

#drv-add by moshuya for fm ant 20240301 start
obj-$(CONFIG_PRI_FM_ANT_SWITCH) += fm_ant/
#drv-add by moshuya for fm ant 20240301 end
obj-$(CONFIG_PRI_LEPTON_FILR)		+= FILR/
#drv add by lipengpeng 20240307 gms adc start
obj-$(CONFIG_DRV_ADC_GMS_DETECT) += gms_adc/
obj-$(CONFIG_CAMERA_TTM)		+= ttm/
obj-$(CONFIG_PRI_AW36406)		+= aw36406/
#drv add by moshuya 20240706 pcbid adc start
obj-$(CONFIG_DRV_ADC_PCBID_DETECT) += pcbid_adc/
#drv add by lipengpeng 20240307 gms adc end
#DRV added by chenjiaxi, add miniscreen driver, start
obj-$(CONFIG_DRV_MINISCREEN) += miniscreen/
#DRV added by chenjiaxi, add miniscreen driver, end
#drv added by chenjiaxi, drv dlpc343x driver, start
obj-$(CONFIG_DRV_DLPC343X) += dlpc343x/
#drv added by chenjiaxi, drv dlpc343x driver, end
#drv added by chenjiaxi, drv coolingfan driver, begin
obj-$(CONFIG_DRV_COOLINGFAN) += coolingfan/
#drv added by chenjiaxi, drv coolingfan driver, end
#drv added by chenjiaxi, aw8646 step driver, begin
obj-$(CONFIG_AW8646_STEP) += aw8646_step/
#drv added by chenjiaxi, aw8646 step driver, end
obj-$(CONFIG_PRI_CAMPING_LIGHT) += camping_light/
#add by driver for press
obj-$(CONFIG_PRIZE_CS_PRESS) += cs_press/

obj-$(CONFIG_AW95016) += aw95016/
#drv-mod by shenwenbin for aw haptic 20250516 start
obj-$(CONFIG_AW86937FCR_HAPTIC_HV) += aw86937fcr_haptic_hv/
#drv-mod by shenwenbin for aw haptic 20250516 end
#drv-add by huangxinglve for oled panel 20250620 start
obj-$(CONFIG_PRIZE_OLED_NODE) += prize_oled_node/
#drv-add by huangxinglve for oled panel 20250620 end

