#makefile

snd-soc-aw882xx-objs +=  aw882xx.o aw882xx_monitor.o aw882xx_bin_parse.o aw882xx_device.o aw882xx_init.o aw882xx_calib.o aw882xx_spin.o aw882xx_dsp.o
obj-$(CONFIG_SND_SOC_AW882XX_V_2_0_0) += snd-soc-aw882xx.o

