#include "../../../drv_common.h"


#if PRI_CD_980S_ATA_CONFIG_1
#define SPI_INDEX spi5
#define FP_IRQ_PIN 13

#define FP_CS_AS_SPI PINMUX_GPIO61__FUNC_SPI1_CSB
#define FP_CK_AS_SPI PINMUX_GPIO60__FUNC_SPI1_CLK
#define FP_MI_AS_SPI PINMUX_GPIO63__FUNC_SPI1_MI
#define FP_MO_AS_SPI PINMUX_GPIO62__FUNC_SPI1_MO

#define FP_CS_AS_GPIO PINMUX_GPIO61__FUNC_GPIO61
#define FP_MI_AS_GPIO PINMUX_GPIO63__FUNC_GPIO63
#define FP_MO_AS_GPIO PINMUX_GPIO62__FUNC_GPIO62

#define FP_RST_AS_GPIO  PINMUX_GPIO1__FUNC_GPIO1
#define FP_INT_AS_GPIO  PINMUX_GPIO13__FUNC_GPIO13

#endif