ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/

obj-m += gt9966f.o
gt9966f-objs := goodix_brl_i2c.o
gt9966f-objs += goodix_brl_spi.o
gt9966f-objs += goodix_ts_core.o
gt9966f-objs += goodix_brl_hw.o
gt9966f-objs += goodix_cfg_bin.o
gt9966f-objs += goodix_ts_utils.o
gt9966f-objs += goodix_brl_fwupdate.o
gt9966f-objs += goodix_ts_gesture.o
gt9966f-objs += goodix_ts_inspect.o
gt9966f-objs += goodix_ts_tools.o
gt9966f-objs += goodix_ts_dump.o
